# Generated by Django 5.1.4 on 2025-01-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المادة')),
                ('description', models.TextField(verbose_name='وصف المادة')),
                ('credit_hours', models.IntegerField(verbose_name='الساعات المعتمدة')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفصل')),
                ('capacity', models.IntegerField(verbose_name='السعة')),
                ('grade_level', models.CharField(max_length=20, verbose_name='المستوى الدراسي')),
                ('academic_year', models.CharField(max_length=9, verbose_name='السنة الدراسية')),
                ('students', models.ManyToManyField(related_name='classes', to='students.student', verbose_name='الطلاب')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=17, verbose_name='رقم الهاتف')),
                ('classes', models.ManyToManyField(related_name='teachers', to='classes.classroom', verbose_name='الفصول التي يدرسها')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='classes.subject', verbose_name='المواد التي يدرسها')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
            },
        ),
    ]
