# Generated by Django 5.1.4 on 2025-01-04 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('semester', 'شهادة فصلية'), ('yearly', 'شهادة سنوية'), ('graduation', 'شهادة تخرج')], max_length=20, verbose_name='نوع الشهادة')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('academic_year', models.CharField(max_length=9, verbose_name='السنة الدراسية')),
                ('grade_level', models.CharField(max_length=20, verbose_name='المستوى الدراسي')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='المعدل التراكمي')),
                ('certificate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الشهادة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'ممتاز'), ('B', 'جيد جداً'), ('C', 'جيد'), ('D', 'مقبول'), ('F', 'راسب')], max_length=1, verbose_name='الدرجة')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النتيجة')),
                ('semester', models.CharField(max_length=20, verbose_name='الفصل الدراسي')),
                ('academic_year', models.CharField(max_length=9, verbose_name='السنة الدراسية')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classroom', verbose_name='الفصل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
                'unique_together': {('student', 'subject', 'semester', 'academic_year')},
            },
        ),
    ]
